[package]
name = "sense-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4", features = ["derive"] }

sc-cli = { package = "sc-cli", git = "https://github.com/paritytech/polkadot-sdk", default-features = true }
